---
- name: Create Launch Agent for Consul
  ansible.builtin.template:
    src: LaunchAgents/homebrew.mxcl.consul.plist.j2
    dest: "{{ launch_agents_dir }}/{{ consul_launchagent_label }}.plist"
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: staff

- name: Start Consul (if not already running)
  block:
    - name: Check if Consul is already running
      ansible.builtin.command:
        argv:
          - launchctl
          - list
          - "{{ consul_launchagent_label }}"
      register: consul_launchctl
      failed_when: false
      changed_when: false

    - name: Load Consul Launch Agent
      when: consul_launchctl.rc != 0
      ansible.builtin.command:
        argv:
          - launchctl
          - bootstrap
          - gui/{{ ansible_user_uid }}
          - "{{ launch_agents_dir }}/{{ consul_launchagent_label }}.plist"
      changed_when: true
