---
namespace: cosmonautical
name: nomadintosh
authors:
  - Violet Caulfield
version: 3.1.0
readme: README.md
description: An Ansible collection for deploying Nomad + Consul on a macOS cluster.
license:
  - MIT
tags:
  - nomad
  - consul
  - macos
  - homelab
  - hashicorp
repository: https://github.com/Cosmonautical-Cloud/Nomadintosh
homepage: https://github.com/Cosmonautical-Cloud/Nomadintosh
issues: https://github.com/Cosmonautical-Cloud/Nomadintosh/issues
dependencies:
  geerlingguy.mac: "*"
  community.general: "*"
  cosmonautical.notify: ">=0.0.1"
