---
- name: Merge release archive lists
  ansible.builtin.set_fact:
    release_archives_merged: >-
      {{ release_archives
         + (query('ansible.builtin.vars', *query('ansible.builtin.varnames', '^release_archives__.+$') | sort) | flatten) }}

- name: Install release archives
  ansible.builtin.include_tasks: archive.yml
  loop: "{{ release_archives_merged }}"
  loop_control:
    loop_var: release_archive
    label: "{{ release_archive.name }} {{ release_archive.version }}"
