---
container_launchagent_label: "com.apple.container"

container_launchagent_program_args:
  - "{{ homebrew_dir }}/bin/container"
  - system
  - start
  - --enable-kernel-install

container_launchagent_log_file: "container.log"
