---
- name: Install Docker Desktop
  community.general.homebrew_cask:
    name: docker-desktop
    state: present
  when: docker.enabled | default(false)

- name: Uninstall Docker Desktop
  community.general.homebrew_cask:
    name: docker-desktop
    state: absent
  when: not (docker.enabled | default(false))
