---
# See README.md for the rationale behind each of these.
nfs_mounts_shares: []
volume_mount_path: /Volumes
nfs_mounts_deadtimeout: 30
nfs_mounts_watchdog_interval: 30
nfs_mounts_version: 3
nfs_mounts_rsize: 65536
nfs_mounts_wsize: 65536
nfs_mounts_timeo: 100
