---
- name: Create tmp directory for Container driver plugin
  ansible.builtin.file:
    path: "{{ nomad_container_driver_tmp_dir }}"
    state: directory
  check_mode: false

- name: Create plugins directory for Nomad
  ansible.builtin.file:
    path: "/opt/nomad/plugins"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "staff"

- name: Download Container driver plugin
  ansible.builtin.get_url:
    url: "{{ nomad_container_driver_url }}"
    dest: "{{ nomad_container_driver_tmp_dir }}/nomad-driver-container-darwin-arm64.tar.gz"
    mode: '0644'
  check_mode: false

- name: Extract Container driver plugin
  ansible.builtin.command:
    argv:
      - /usr/bin/tar
      - xzf
      - "{{ nomad_container_driver_tmp_dir }}/nomad-driver-container-darwin-arm64.tar.gz"
      - -C
      - "{{ nomad_container_driver_tmp_dir }}"
    creates: "{{ nomad_container_driver_tmp_dir }}/nomad-driver-container"
  check_mode: false

- name: Move Container driver plugin to Nomad plugins directory
  ansible.builtin.copy:
    src: "{{ nomad_container_driver_tmp_dir }}/nomad-driver-container"
    dest: "/opt/nomad/plugins/{{ nomad_container_driver_name }}"
    remote_src: true
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "staff"
  check_mode: false
