---
galaxy_info:
  author: Violet Caulfield
  description: Installs SeaweedFS via Homebrew, and creates the directory backing a host's SeaweedFS volume.
  license: MIT
  min_ansible_version: "2.15"
dependencies: []
